name: codecov

on: [push, pull_request]

env:
  BUILD_TYPE: Debug
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      shell: bash
      run: cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DYYJSON_BUILD_TEST=ON -DENABLE_TEST_COVERAGE=1

    - name: Build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      run: |
        cd build
        ctest -C $BUILD_TYPE

    - name: Codecov
      shell: bash
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
